name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  lint-and-test:
    name: Run eslint and test
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: postgres://postgres:a@localhost:5432/webDb
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: a
          POSTGRES_USER: postgres
          POSTGRES_DB: webDb
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    container:
      image: node
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        uses: borales/actions-yarn@v2.1.0
        with:
          cmd: install
      - name: create env file
        run: echo DATABASE_URL=${{ env.DATABASE_URL }} >> .env
      - name: migrate
        uses: borales/actions-yarn@v2.1.0
        with:
          cmd: prisma
      - name: Lint
        uses: borales/actions-yarn@v2.1.0
        with:
          cmd: lint
      - name: Tests
        uses: borales/actions-yarn@v2.1.0
        with:
          cmd: test
  build:
    name: Build docker container
    runs-on: ubuntu-latest
    needs: lint-and-test
    steps:
      - uses: actions/checkout@v2
      - name: Login to github docker
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build docker image
        run: docker build -t api .
      - name: Docker tag
        run: docker tag api ${{ secrets.DOCKER_USER }}/api-webdev-uni:latest
      - name: Push docker image
        run: docker push ${{ secrets.DOCKER_USER }}/api-webdev-uni:latest
