name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  lint-and-test:
    name: Run eslint
    runs-on: ubuntu-latest
    container:
      image: node
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        uses: borales/actions-yarn@v2.1.0
        with:
          cmd: install
      - name: Lint
        uses: borales/actions-yarn@v2.1.0
        with:
          cmd: lint
      - name: test
        uses: borales/actions-yarn@v2.1.0
        with:
          cmd: test
  #test:
  #name: Test tests
  #runs-on: ubuntu-latest
  #needs: lint
  #steps:
  #- uses: actions/checkout@v2
  # - name: Install dependencies
  #uses: borales/actions-yarn@v2.1.0
  #with:
  #cmd: install
  #- name: test
  #uses: borales/actions-yarn@v2.1.0
  #with:
  #cmd: test
