name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  lint-and-test:
    name: Run eslint and test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: a
          POSTGRES_USER: postgres
          POSTGRES_DB: webDb
    container:
      image: node
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        uses: borales/actions-yarn@v2.1.0
        with:
          cmd: install
      - name: Lint
        uses: borales/actions-yarn@v2.1.0
        with:
          cmd: lint
      - name: Tests
        uses: borales/actions-yarn@v2.1.0
        with:
          cmd: test
        env:
          DATABASE_URL: postgres://postgres:A@localhost:5432/webDb
  build:
    name: Build docker container
    runs-on: ubuntu-latest
    needs: lint-and-test
    steps:
      - uses: actions/checkout@v2
      - name: Login to github docker
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build docker image
        run: docker build -t api .
      - name: Docker tag
        run: docker tag api ${{ secrets.DOCKER_USER }}/api-webdev-uni:latest
      - name: Push docker image
        run: docker push ${{ secrets.DOCKER_USER }}/api-webdev-uni:latest
